/**
 * Persona
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Persona) {
      root.Persona = {};
    }
    root.Persona.ActiveDays = factory(root.Persona.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The ActiveDays model module.
   * @module model/ActiveDays
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>ActiveDays</code>.
   * @alias module:model/ActiveDays
   * @class
   * @param mon {Boolean} Active on Monday
   * @param tue {Boolean} Active on Tuesday
   * @param wed {Boolean} Active on Wednedsday
   * @param thu {Boolean} Active on Thursday
   * @param fri {Boolean} Active on Friday
   * @param sat {Boolean} Active on Saturday
   * @param sun {Boolean} Active on Sunday
   */
  var exports = function(mon, tue, wed, thu, fri, sat, sun) {
    var _this = this;

    _this['mon'] = mon;
    _this['tue'] = tue;
    _this['wed'] = wed;
    _this['thu'] = thu;
    _this['fri'] = fri;
    _this['sat'] = sat;
    _this['sun'] = sun;
  };

  /**
   * Constructs a <code>ActiveDays</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ActiveDays} obj Optional instance to populate.
   * @return {module:model/ActiveDays} The populated <code>ActiveDays</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('mon')) {
        obj['mon'] = ApiClient.convertToType(data['mon'], 'Boolean');
      }
      if (data.hasOwnProperty('tue')) {
        obj['tue'] = ApiClient.convertToType(data['tue'], 'Boolean');
      }
      if (data.hasOwnProperty('wed')) {
        obj['wed'] = ApiClient.convertToType(data['wed'], 'Boolean');
      }
      if (data.hasOwnProperty('thu')) {
        obj['thu'] = ApiClient.convertToType(data['thu'], 'Boolean');
      }
      if (data.hasOwnProperty('fri')) {
        obj['fri'] = ApiClient.convertToType(data['fri'], 'Boolean');
      }
      if (data.hasOwnProperty('sat')) {
        obj['sat'] = ApiClient.convertToType(data['sat'], 'Boolean');
      }
      if (data.hasOwnProperty('sun')) {
        obj['sun'] = ApiClient.convertToType(data['sun'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * Active on Monday
   * @member {Boolean} mon
   */
  exports.prototype['mon'] = undefined;
  /**
   * Active on Tuesday
   * @member {Boolean} tue
   */
  exports.prototype['tue'] = undefined;
  /**
   * Active on Wednedsday
   * @member {Boolean} wed
   */
  exports.prototype['wed'] = undefined;
  /**
   * Active on Thursday
   * @member {Boolean} thu
   */
  exports.prototype['thu'] = undefined;
  /**
   * Active on Friday
   * @member {Boolean} fri
   */
  exports.prototype['fri'] = undefined;
  /**
   * Active on Saturday
   * @member {Boolean} sat
   */
  exports.prototype['sat'] = undefined;
  /**
   * Active on Sunday
   * @member {Boolean} sun
   */
  exports.prototype['sun'] = undefined;



  return exports;
}));


