/**
 * Persona
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Persona) {
      root.Persona = {};
    }
    root.Persona.CancelSubscriptionReason = factory(root.Persona.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The CancelSubscriptionReason model module.
   * @module model/CancelSubscriptionReason
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>CancelSubscriptionReason</code>.
   * Cancel reason
   * @alias module:model/CancelSubscriptionReason
   * @class
   * @param reason {module:model/CancelSubscriptionReason.ReasonEnum} Cancel reason code
   */
  var exports = function(reason) {
    var _this = this;

    _this['reason'] = reason;
  };

  /**
   * Constructs a <code>CancelSubscriptionReason</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CancelSubscriptionReason} obj Optional instance to populate.
   * @return {module:model/CancelSubscriptionReason} The populated <code>CancelSubscriptionReason</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('reason')) {
        obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
      }
      if (data.hasOwnProperty('notes')) {
        obj['notes'] = ApiClient.convertToType(data['notes'], 'String');
      }
    }
    return obj;
  }

  /**
   * Cancel reason code
   * @member {module:model/CancelSubscriptionReason.ReasonEnum} reason
   */
  exports.prototype['reason'] = undefined;
  /**
   * Cancel reason explanation
   * @member {String} notes
   */
  exports.prototype['notes'] = undefined;


  /**
   * Allowed values for the <code>reason</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ReasonEnum = {
    /**
     * value: "Price"
     * @const
     */
    "Price": "Price",
    /**
     * value: "Distribution"
     * @const
     */
    "Distribution": "Distribution",
    /**
     * value: "Content"
     * @const
     */
    "Content": "Content",
    /**
     * value: "OldAge"
     * @const
     */
    "OldAge": "OldAge",
    /**
     * value: "Deceased"
     * @const
     */
    "Deceased": "Deceased",
    /**
     * value: "Digital"
     * @const
     */
    "Digital": "Digital",
    /**
     * value: "Other"
     * @const
     */
    "Other": "Other",
    /**
     * value: "ChangeProduct"
     * @const
     */
    "ChangeProduct": "ChangeProduct"  };


  return exports;
}));


