/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DescriptionFrequency model module.
 * @module model/DescriptionFrequency
 * @version 1.3.0
 */
class DescriptionFrequency {
    /**
     * Constructs a new <code>DescriptionFrequency</code>.
     * @alias module:model/DescriptionFrequency
     * @param amount {Number} 
     * @param unit {String} 
     */
    constructor(amount, unit) { 
        
        DescriptionFrequency.initialize(this, amount, unit);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, amount, unit) { 
        obj['amount'] = amount;
        obj['unit'] = unit;
    }

    /**
     * Constructs a <code>DescriptionFrequency</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DescriptionFrequency} obj Optional instance to populate.
     * @return {module:model/DescriptionFrequency} The populated <code>DescriptionFrequency</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DescriptionFrequency();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('unit')) {
                obj['unit'] = ApiClient.convertToType(data['unit'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} amount
 */
DescriptionFrequency.prototype['amount'] = undefined;

/**
 * @member {String} unit
 */
DescriptionFrequency.prototype['unit'] = undefined;






export default DescriptionFrequency;

