/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Persona) {
      root.Persona = {};
    }
    root.Persona.GdprConsent = factory(root.Persona.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The GdprConsent model module.
   * @module model/GdprConsent
   * @version 1.2.0
   */

  /**
   * Constructs a new <code>GdprConsent</code>.
   * @alias module:model/GdprConsent
   * @class
   * @param key {String} 
   * @param val {Boolean} 
   */
  var exports = function(key, val) {
    var _this = this;

    _this['key'] = key;
    _this['val'] = val;
  };

  /**
   * Constructs a <code>GdprConsent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GdprConsent} obj Optional instance to populate.
   * @return {module:model/GdprConsent} The populated <code>GdprConsent</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('key')) {
        obj['key'] = ApiClient.convertToType(data['key'], 'String');
      }
      if (data.hasOwnProperty('val')) {
        obj['val'] = ApiClient.convertToType(data['val'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {String} key
   */
  exports.prototype['key'] = undefined;
  /**
   * @member {Boolean} val
   */
  exports.prototype['val'] = undefined;



  return exports;
}));


