/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse4032EmailAddressInUse model module.
 * @module model/InlineResponse4032EmailAddressInUse
 * @version 1.3.0
 */
class InlineResponse4032EmailAddressInUse {
    /**
     * Constructs a new <code>InlineResponse4032EmailAddressInUse</code>.
     * @alias module:model/InlineResponse4032EmailAddressInUse
     */
    constructor() { 
        
        InlineResponse4032EmailAddressInUse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse4032EmailAddressInUse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse4032EmailAddressInUse} obj Optional instance to populate.
     * @return {module:model/InlineResponse4032EmailAddressInUse} The populated <code>InlineResponse4032EmailAddressInUse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse4032EmailAddressInUse();

            if (data.hasOwnProperty('merge_token')) {
                obj['merge_token'] = ApiClient.convertToType(data['merge_token'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('existing_provider')) {
                obj['existing_provider'] = ApiClient.convertToType(data['existing_provider'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} merge_token
 */
InlineResponse4032EmailAddressInUse.prototype['merge_token'] = undefined;

/**
 * @member {module:model/InlineResponse4032EmailAddressInUse.DescriptionEnum} description
 */
InlineResponse4032EmailAddressInUse.prototype['description'] = undefined;

/**
 * @member {String} existing_provider
 */
InlineResponse4032EmailAddressInUse.prototype['existing_provider'] = undefined;





/**
 * Allowed values for the <code>description</code> property.
 * @enum {String}
 * @readonly
 */
InlineResponse4032EmailAddressInUse['DescriptionEnum'] = {

    /**
     * value: "User has another record registered. Please merge the accounts."
     * @const
     */
    "User has another record registered. Please merge the accounts.": "User has another record registered. Please merge the accounts."
};



export default InlineResponse4032EmailAddressInUse;

