/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse400InvalidRequestBody from './InlineResponse400InvalidRequestBody';

/**
 * The InlineResponse400 model module.
 * @module model/InlineResponse400
 * @version 1.3.0
 */
class InlineResponse400 {
    /**
     * Constructs a new <code>InlineResponse400</code>.
     * @alias module:model/InlineResponse400
     */
    constructor() { 
        
        InlineResponse400.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse400</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse400} obj Optional instance to populate.
     * @return {module:model/InlineResponse400} The populated <code>InlineResponse400</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse400();

            if (data.hasOwnProperty('http_code')) {
                obj['http_code'] = ApiClient.convertToType(data['http_code'], 'Number');
            }
            if (data.hasOwnProperty('invalid_request_body')) {
                obj['invalid_request_body'] = InlineResponse400InvalidRequestBody.constructFromObject(data['invalid_request_body']);
            }
            if (data.hasOwnProperty('http_status')) {
                obj['http_status'] = ApiClient.convertToType(data['http_status'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} http_code
 */
InlineResponse400.prototype['http_code'] = undefined;

/**
 * @member {module:model/InlineResponse400InvalidRequestBody} invalid_request_body
 */
InlineResponse400.prototype['invalid_request_body'] = undefined;

/**
 * @member {module:model/InlineResponse400.HttpStatusEnum} http_status
 */
InlineResponse400.prototype['http_status'] = undefined;





/**
 * Allowed values for the <code>http_status</code> property.
 * @enum {String}
 * @readonly
 */
InlineResponse400['HttpStatusEnum'] = {

    /**
     * value: "Bad request"
     * @const
     */
    "Bad request": "Bad request"
};



export default InlineResponse400;

