/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse500InternalServerError'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse500InternalServerError'));
  } else {
    // Browser globals (root is window)
    if (!root.PersonaClient) {
      root.PersonaClient = {};
    }
    root.PersonaClient.InlineResponse500 = factory(root.PersonaClient.ApiClient, root.PersonaClient.InlineResponse500InternalServerError);
  }
}(this, function(ApiClient, InlineResponse500InternalServerError) {
  'use strict';



  /**
   * The InlineResponse500 model module.
   * @module model/InlineResponse500
   * @version 1.2.0
   */

  /**
   * Constructs a new <code>InlineResponse500</code>.
   * @alias module:model/InlineResponse500
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>InlineResponse500</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse500} obj Optional instance to populate.
   * @return {module:model/InlineResponse500} The populated <code>InlineResponse500</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('http_code')) {
        obj['http_code'] = ApiClient.convertToType(data['http_code'], 'Number');
      }
      if (data.hasOwnProperty('http_status')) {
        obj['http_status'] = ApiClient.convertToType(data['http_status'], 'String');
      }
      if (data.hasOwnProperty('internal_server_error')) {
        obj['internal_server_error'] = InlineResponse500InternalServerError.constructFromObject(data['internal_server_error']);
      }
    }
    return obj;
  }

  /**
   * @member {Number} http_code
   */
  exports.prototype['http_code'] = undefined;
  /**
   * @member {module:model/InlineResponse500.HttpStatusEnum} http_status
   */
  exports.prototype['http_status'] = undefined;
  /**
   * @member {module:model/InlineResponse500InternalServerError} internal_server_error
   */
  exports.prototype['internal_server_error'] = undefined;


  /**
   * Allowed values for the <code>http_status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.HttpStatusEnum = {
    /**
     * value: "Internal server error"
     * @const
     */
    "Internal server error": "Internal server error"  };


  return exports;
}));


