/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InlineResponse403InvalidCredentials'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InlineResponse403InvalidCredentials'));
  } else {
    // Browser globals (root is window)
    if (!root.PersonaClient) {
      root.PersonaClient = {};
    }
    root.PersonaClient.InlineResponse403 = factory(root.PersonaClient.ApiClient, root.PersonaClient.InlineResponse403InvalidCredentials);
  }
}(this, function(ApiClient, InlineResponse403InvalidCredentials) {
  'use strict';



  /**
   * The InlineResponse403 model module.
   * @module model/InlineResponse403
   * @version 1.2.0
   */

  /**
   * Constructs a new <code>InlineResponse403</code>.
   * @alias module:model/InlineResponse403
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>InlineResponse403</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse403} obj Optional instance to populate.
   * @return {module:model/InlineResponse403} The populated <code>InlineResponse403</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('http_code')) {
        obj['http_code'] = ApiClient.convertToType(data['http_code'], 'Number');
      }
      if (data.hasOwnProperty('http_status')) {
        obj['http_status'] = ApiClient.convertToType(data['http_status'], 'String');
      }
      if (data.hasOwnProperty('invalid_credentials')) {
        obj['invalid_credentials'] = InlineResponse403InvalidCredentials.constructFromObject(data['invalid_credentials']);
      }
    }
    return obj;
  }

  /**
   * @member {Number} http_code
   */
  exports.prototype['http_code'] = undefined;
  /**
   * @member {module:model/InlineResponse403.HttpStatusEnum} http_status
   */
  exports.prototype['http_status'] = undefined;
  /**
   * @member {module:model/InlineResponse403InvalidCredentials} invalid_credentials
   */
  exports.prototype['invalid_credentials'] = undefined;


  /**
   * Allowed values for the <code>http_status</code> property.
   * @enum {String}
   * @readonly
   */
  exports.HttpStatusEnum = {
    /**
     * value: "Forbidden"
     * @const
     */
    "Forbidden": "Forbidden"  };


  return exports;
}));


