/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InlineResponse4032EmailAddressInUse from './InlineResponse4032EmailAddressInUse';
import InlineResponse4032EmailNotAuthorized from './InlineResponse4032EmailNotAuthorized';
import InlineResponse4032OauthFailed from './InlineResponse4032OauthFailed';

/**
 * The InlineResponse4032 model module.
 * @module model/InlineResponse4032
 * @version 1.3.0
 */
class InlineResponse4032 {
    /**
     * Constructs a new <code>InlineResponse4032</code>.
     * @alias module:model/InlineResponse4032
     */
    constructor() { 
        
        InlineResponse4032.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse4032</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse4032} obj Optional instance to populate.
     * @return {module:model/InlineResponse4032} The populated <code>InlineResponse4032</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse4032();

            if (data.hasOwnProperty('email_address_in_use')) {
                obj['email_address_in_use'] = InlineResponse4032EmailAddressInUse.constructFromObject(data['email_address_in_use']);
            }
            if (data.hasOwnProperty('http_code')) {
                obj['http_code'] = ApiClient.convertToType(data['http_code'], 'Number');
            }
            if (data.hasOwnProperty('oauth_failed')) {
                obj['oauth_failed'] = InlineResponse4032OauthFailed.constructFromObject(data['oauth_failed']);
            }
            if (data.hasOwnProperty('http_status')) {
                obj['http_status'] = ApiClient.convertToType(data['http_status'], 'String');
            }
            if (data.hasOwnProperty('email_not_authorized')) {
                obj['email_not_authorized'] = InlineResponse4032EmailNotAuthorized.constructFromObject(data['email_not_authorized']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/InlineResponse4032EmailAddressInUse} email_address_in_use
 */
InlineResponse4032.prototype['email_address_in_use'] = undefined;

/**
 * @member {Number} http_code
 */
InlineResponse4032.prototype['http_code'] = undefined;

/**
 * @member {module:model/InlineResponse4032OauthFailed} oauth_failed
 */
InlineResponse4032.prototype['oauth_failed'] = undefined;

/**
 * @member {module:model/InlineResponse4032.HttpStatusEnum} http_status
 */
InlineResponse4032.prototype['http_status'] = undefined;

/**
 * @member {module:model/InlineResponse4032EmailNotAuthorized} email_not_authorized
 */
InlineResponse4032.prototype['email_not_authorized'] = undefined;





/**
 * Allowed values for the <code>http_status</code> property.
 * @enum {String}
 * @readonly
 */
InlineResponse4032['HttpStatusEnum'] = {

    /**
     * value: "Forbidden"
     * @const
     */
    "Forbidden": "Forbidden"
};



export default InlineResponse4032;

