/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The InlineResponse403InvalidCredentials model module.
 * @module model/InlineResponse403InvalidCredentials
 * @version 1.3.0
 */
class InlineResponse403InvalidCredentials {
    /**
     * Constructs a new <code>InlineResponse403InvalidCredentials</code>.
     * @alias module:model/InlineResponse403InvalidCredentials
     */
    constructor() { 
        
        InlineResponse403InvalidCredentials.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineResponse403InvalidCredentials</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineResponse403InvalidCredentials} obj Optional instance to populate.
     * @return {module:model/InlineResponse403InvalidCredentials} The populated <code>InlineResponse403InvalidCredentials</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse403InvalidCredentials();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/InlineResponse403InvalidCredentials.DescriptionEnum} description
 */
InlineResponse403InvalidCredentials.prototype['description'] = undefined;





/**
 * Allowed values for the <code>description</code> property.
 * @enum {String}
 * @readonly
 */
InlineResponse403InvalidCredentials['DescriptionEnum'] = {

    /**
     * value: "Wrong username or password"
     * @const
     */
    "Wrong username or password": "Wrong username or password"
};



export default InlineResponse403InvalidCredentials;

