/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LoginData model module.
 * @module model/LoginData
 * @version 1.3.0
 */
class LoginData {
    /**
     * Constructs a new <code>LoginData</code>.
     * @alias module:model/LoginData
     * @param username {String} 
     * @param password {String} 
     */
    constructor(username, password) { 
        
        LoginData.initialize(this, username, password);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, username, password) { 
        obj['username'] = username;
        obj['password'] = password;
    }

    /**
     * Constructs a <code>LoginData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LoginData} obj Optional instance to populate.
     * @return {module:model/LoginData} The populated <code>LoginData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoginData();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('mergeToken')) {
                obj['mergeToken'] = ApiClient.convertToType(data['mergeToken'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} username
 */
LoginData.prototype['username'] = undefined;

/**
 * @member {String} password
 */
LoginData.prototype['password'] = undefined;

/**
 * @member {String} mergeToken
 */
LoginData.prototype['mergeToken'] = undefined;






export default LoginData;

