/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LoginDataSoMe model module.
 * @module model/LoginDataSoMe
 * @version 1.3.0
 */
class LoginDataSoMe {
    /**
     * Constructs a new <code>LoginDataSoMe</code>.
     * @alias module:model/LoginDataSoMe
     * @param provider {String} 
     * @param someToken {String} 
     */
    constructor(provider, someToken) { 
        
        LoginDataSoMe.initialize(this, provider, someToken);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, provider, someToken) { 
        obj['provider'] = provider;
        obj['someToken'] = someToken;
    }

    /**
     * Constructs a <code>LoginDataSoMe</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LoginDataSoMe} obj Optional instance to populate.
     * @return {module:model/LoginDataSoMe} The populated <code>LoginDataSoMe</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoginDataSoMe();

            if (data.hasOwnProperty('provider')) {
                obj['provider'] = ApiClient.convertToType(data['provider'], 'String');
            }
            if (data.hasOwnProperty('someToken')) {
                obj['someToken'] = ApiClient.convertToType(data['someToken'], 'String');
            }
            if (data.hasOwnProperty('mergeToken')) {
                obj['mergeToken'] = ApiClient.convertToType(data['mergeToken'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} provider
 */
LoginDataSoMe.prototype['provider'] = undefined;

/**
 * @member {String} someToken
 */
LoginDataSoMe.prototype['someToken'] = undefined;

/**
 * @member {String} mergeToken
 */
LoginDataSoMe.prototype['mergeToken'] = undefined;






export default LoginDataSoMe;

