/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LoginDataSSO model module.
 * @module model/LoginDataSSO
 * @version 1.3.0
 */
class LoginDataSSO {
    /**
     * Constructs a new <code>LoginDataSSO</code>.
     * @alias module:model/LoginDataSSO
     * @param uuid {String} 
     * @param accessToken {String} 
     */
    constructor(uuid, accessToken) { 
        
        LoginDataSSO.initialize(this, uuid, accessToken);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, uuid, accessToken) { 
        obj['uuid'] = uuid;
        obj['accessToken'] = accessToken;
    }

    /**
     * Constructs a <code>LoginDataSSO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LoginDataSSO} obj Optional instance to populate.
     * @return {module:model/LoginDataSSO} The populated <code>LoginDataSSO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoginDataSSO();

            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('accessToken')) {
                obj['accessToken'] = ApiClient.convertToType(data['accessToken'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} uuid
 */
LoginDataSSO.prototype['uuid'] = undefined;

/**
 * @member {String} accessToken
 */
LoginDataSSO.prototype['accessToken'] = undefined;






export default LoginDataSSO;

