/**
 * Persona
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PaperCode'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PaperCode'));
  } else {
    // Browser globals (root is window)
    if (!root.Persona) {
      root.Persona = {};
    }
    root.Persona.NewDeliveryReclamation = factory(root.Persona.ApiClient, root.Persona.PaperCode);
  }
}(this, function(ApiClient, PaperCode) {
  'use strict';



  /**
   * The NewDeliveryReclamation model module.
   * @module model/NewDeliveryReclamation
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>NewDeliveryReclamation</code>.
   * Data for a delivery reclamation creation.
   * @alias module:model/NewDeliveryReclamation
   * @class
   * @param publicationDate {Date} 
   * @param claim {module:model/NewDeliveryReclamation.ClaimEnum} The type of claim for the reclamation
   */
  var exports = function(publicationDate, claim) {
    var _this = this;

    _this['publicationDate'] = publicationDate;
    _this['claim'] = claim;
  };

  /**
   * Constructs a <code>NewDeliveryReclamation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NewDeliveryReclamation} obj Optional instance to populate.
   * @return {module:model/NewDeliveryReclamation} The populated <code>NewDeliveryReclamation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('paper')) {
        obj['paper'] = PaperCode.constructFromObject(data['paper']);
      }
      if (data.hasOwnProperty('publicationDate')) {
        obj['publicationDate'] = ApiClient.convertToType(data['publicationDate'], 'Date');
      }
      if (data.hasOwnProperty('claim')) {
        obj['claim'] = ApiClient.convertToType(data['claim'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/PaperCode} paper
   */
  exports.prototype['paper'] = undefined;
  /**
   * @member {Date} publicationDate
   */
  exports.prototype['publicationDate'] = undefined;
  /**
   * The type of claim for the reclamation
   * @member {module:model/NewDeliveryReclamation.ClaimEnum} claim
   */
  exports.prototype['claim'] = undefined;


  /**
   * Allowed values for the <code>claim</code> property.
   * @enum {String}
   * @readonly
   */
  exports.ClaimEnum = {
    /**
     * value: "Extension"
     * @const
     */
    "Extension": "Extension",
    /**
     * value: "NewDelivery"
     * @const
     */
    "NewDelivery": "NewDelivery"  };


  return exports;
}));


