/**
 * Persona
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/NewsletterSubscription'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./NewsletterSubscription'));
  } else {
    // Browser globals (root is window)
    if (!root.Persona) {
      root.Persona = {};
    }
    root.Persona.Newsletter = factory(root.Persona.ApiClient, root.Persona.NewsletterSubscription);
  }
}(this, function(ApiClient, NewsletterSubscription) {
  'use strict';



  /**
   * The Newsletter model module.
   * @module model/Newsletter
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>Newsletter</code>.
   * @alias module:model/Newsletter
   * @class
   * @param listId {String} 
   * @param paper {String} 
   * @param subscriptions {Object.<String, Array.<module:model/NewsletterSubscription>>} 
   */
  var exports = function(listId, paper, subscriptions) {
    var _this = this;

    _this['listId'] = listId;
    _this['paper'] = paper;
    _this['subscriptions'] = subscriptions;
  };

  /**
   * Constructs a <code>Newsletter</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Newsletter} obj Optional instance to populate.
   * @return {module:model/Newsletter} The populated <code>Newsletter</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('listId')) {
        obj['listId'] = ApiClient.convertToType(data['listId'], 'String');
      }
      if (data.hasOwnProperty('paper')) {
        obj['paper'] = ApiClient.convertToType(data['paper'], 'String');
      }
      if (data.hasOwnProperty('subscriptions')) {
        obj['subscriptions'] = ApiClient.convertToType(data['subscriptions'], {'String': [NewsletterSubscription]});
      }
    }
    return obj;
  }

  /**
   * @member {String} listId
   */
  exports.prototype['listId'] = undefined;
  /**
   * @member {String} paper
   */
  exports.prototype['paper'] = undefined;
  /**
   * @member {Object.<String, Array.<module:model/NewsletterSubscription>>} subscriptions
   */
  exports.prototype['subscriptions'] = undefined;



  return exports;
}));


