/**
 * Persona
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Persona) {
      root.Persona = {};
    }
    root.Persona.NewsletterSubscriptions = factory(root.Persona.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The NewsletterSubscriptions model module.
   * @module model/NewsletterSubscriptions
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>NewsletterSubscriptions</code>.
   * @alias module:model/NewsletterSubscriptions
   * @class
   */
  var exports = function() {
    var _this = this;

  };

  /**
   * Constructs a <code>NewsletterSubscriptions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NewsletterSubscriptions} obj Optional instance to populate.
   * @return {module:model/NewsletterSubscriptions} The populated <code>NewsletterSubscriptions</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('norden')) {
        obj['norden'] = ApiClient.convertToType(data['norden'], 'Boolean');
      }
      if (data.hasOwnProperty('daily')) {
        obj['daily'] = ApiClient.convertToType(data['daily'], 'Boolean');
      }
      if (data.hasOwnProperty('kultur')) {
        obj['kultur'] = ApiClient.convertToType(data['kultur'], 'Boolean');
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} norden
   */
  exports.prototype['norden'] = undefined;
  /**
   * @member {Boolean} daily
   */
  exports.prototype['daily'] = undefined;
  /**
   * @member {Boolean} kultur
   */
  exports.prototype['kultur'] = undefined;



  return exports;
}));


