/**
 * Persona
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/LegalConsent'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./LegalConsent'));
  } else {
    // Browser globals (root is window)
    if (!root.Persona) {
      root.Persona = {};
    }
    root.Persona.NewTemporaryUser = factory(root.Persona.ApiClient, root.Persona.LegalConsent);
  }
}(this, function(ApiClient, LegalConsent) {
  'use strict';



  /**
   * The NewTemporaryUser model module.
   * @module model/NewTemporaryUser
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>NewTemporaryUser</code>.
   * @alias module:model/NewTemporaryUser
   * @class
   * @param emailAddress {String} 
   * @param legalConsents {Array.<module:model/LegalConsent>} 
   */
  var exports = function(emailAddress, legalConsents) {
    var _this = this;

    _this['emailAddress'] = emailAddress;
    _this['legalConsents'] = legalConsents;
  };

  /**
   * Constructs a <code>NewTemporaryUser</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/NewTemporaryUser} obj Optional instance to populate.
   * @return {module:model/NewTemporaryUser} The populated <code>NewTemporaryUser</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('emailAddress')) {
        obj['emailAddress'] = ApiClient.convertToType(data['emailAddress'], 'String');
      }
      if (data.hasOwnProperty('legalConsents')) {
        obj['legalConsents'] = ApiClient.convertToType(data['legalConsents'], [LegalConsent]);
      }
    }
    return obj;
  }

  /**
   * @member {String} emailAddress
   */
  exports.prototype['emailAddress'] = undefined;
  /**
   * @member {Array.<module:model/LegalConsent>} legalConsents
   */
  exports.prototype['legalConsents'] = undefined;



  return exports;
}));


