/**
 * Persona
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DescriptionFrequency'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DescriptionFrequency'));
  } else {
    // Browser globals (root is window)
    if (!root.Persona) {
      root.Persona = {};
    }
    root.Persona.PackageDescription = factory(root.Persona.ApiClient, root.Persona.DescriptionFrequency);
  }
}(this, function(ApiClient, DescriptionFrequency) {
  'use strict';



  /**
   * The PackageDescription model module.
   * @module model/PackageDescription
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>PackageDescription</code>.
   * @alias module:model/PackageDescription
   * @class
   * @param brand {String} Brand name
   * @param brandLong {String} Brand name, long
   * @param descShort {String} Short description
   * @param descLong {String} Long description
   * @param url {String} Url for the current package
   * @param days {String} How many days the package is active
   * @param weekdays {String} Weekdays for which the package is active
   * @param frequency {module:model/DescriptionFrequency} 
   * @param includes {Array.<String>} Entitlements included in the package
   */
  var exports = function(brand, brandLong, descShort, descLong, url, days, weekdays, frequency, includes) {
    var _this = this;

    _this['brand'] = brand;
    _this['brandLong'] = brandLong;
    _this['descShort'] = descShort;
    _this['descLong'] = descLong;
    _this['url'] = url;
    _this['days'] = days;
    _this['weekdays'] = weekdays;
    _this['frequency'] = frequency;
    _this['includes'] = includes;
  };

  /**
   * Constructs a <code>PackageDescription</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PackageDescription} obj Optional instance to populate.
   * @return {module:model/PackageDescription} The populated <code>PackageDescription</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('brand')) {
        obj['brand'] = ApiClient.convertToType(data['brand'], 'String');
      }
      if (data.hasOwnProperty('brandLong')) {
        obj['brandLong'] = ApiClient.convertToType(data['brandLong'], 'String');
      }
      if (data.hasOwnProperty('descShort')) {
        obj['descShort'] = ApiClient.convertToType(data['descShort'], 'String');
      }
      if (data.hasOwnProperty('descLong')) {
        obj['descLong'] = ApiClient.convertToType(data['descLong'], 'String');
      }
      if (data.hasOwnProperty('url')) {
        obj['url'] = ApiClient.convertToType(data['url'], 'String');
      }
      if (data.hasOwnProperty('days')) {
        obj['days'] = ApiClient.convertToType(data['days'], 'String');
      }
      if (data.hasOwnProperty('weekdays')) {
        obj['weekdays'] = ApiClient.convertToType(data['weekdays'], 'String');
      }
      if (data.hasOwnProperty('frequency')) {
        obj['frequency'] = DescriptionFrequency.constructFromObject(data['frequency']);
      }
      if (data.hasOwnProperty('includes')) {
        obj['includes'] = ApiClient.convertToType(data['includes'], ['String']);
      }
    }
    return obj;
  }

  /**
   * Brand name
   * @member {String} brand
   */
  exports.prototype['brand'] = undefined;
  /**
   * Brand name, long
   * @member {String} brandLong
   */
  exports.prototype['brandLong'] = undefined;
  /**
   * Short description
   * @member {String} descShort
   */
  exports.prototype['descShort'] = undefined;
  /**
   * Long description
   * @member {String} descLong
   */
  exports.prototype['descLong'] = undefined;
  /**
   * Url for the current package
   * @member {String} url
   */
  exports.prototype['url'] = undefined;
  /**
   * How many days the package is active
   * @member {String} days
   */
  exports.prototype['days'] = undefined;
  /**
   * Weekdays for which the package is active
   * @member {String} weekdays
   */
  exports.prototype['weekdays'] = undefined;
  /**
   * @member {module:model/DescriptionFrequency} frequency
   */
  exports.prototype['frequency'] = undefined;
  /**
   * Entitlements included in the package
   * @member {Array.<String>} includes
   */
  exports.prototype['includes'] = undefined;



  return exports;
}));


