/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DescriptionFrequency from './DescriptionFrequency';

/**
 * The PackageDescription model module.
 * @module model/PackageDescription
 * @version 1.3.0
 */
class PackageDescription {
    /**
     * Constructs a new <code>PackageDescription</code>.
     * @alias module:model/PackageDescription
     * @param brand {String} 
     * @param brandLong {String} 
     * @param descShort {String} 
     * @param descLong {String} 
     * @param url {String} 
     * @param days {String} 
     * @param weekdays {String} 
     * @param frequency {module:model/DescriptionFrequency} 
     * @param includes {Array.<String>} 
     */
    constructor(brand, brandLong, descShort, descLong, url, days, weekdays, frequency, includes) { 
        
        PackageDescription.initialize(this, brand, brandLong, descShort, descLong, url, days, weekdays, frequency, includes);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, brand, brandLong, descShort, descLong, url, days, weekdays, frequency, includes) { 
        obj['brand'] = brand;
        obj['brandLong'] = brandLong;
        obj['descShort'] = descShort;
        obj['descLong'] = descLong;
        obj['url'] = url;
        obj['days'] = days;
        obj['weekdays'] = weekdays;
        obj['frequency'] = frequency;
        obj['includes'] = includes;
    }

    /**
     * Constructs a <code>PackageDescription</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PackageDescription} obj Optional instance to populate.
     * @return {module:model/PackageDescription} The populated <code>PackageDescription</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PackageDescription();

            if (data.hasOwnProperty('brand')) {
                obj['brand'] = ApiClient.convertToType(data['brand'], 'String');
            }
            if (data.hasOwnProperty('brandLong')) {
                obj['brandLong'] = ApiClient.convertToType(data['brandLong'], 'String');
            }
            if (data.hasOwnProperty('descShort')) {
                obj['descShort'] = ApiClient.convertToType(data['descShort'], 'String');
            }
            if (data.hasOwnProperty('descLong')) {
                obj['descLong'] = ApiClient.convertToType(data['descLong'], 'String');
            }
            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('days')) {
                obj['days'] = ApiClient.convertToType(data['days'], 'String');
            }
            if (data.hasOwnProperty('weekdays')) {
                obj['weekdays'] = ApiClient.convertToType(data['weekdays'], 'String');
            }
            if (data.hasOwnProperty('frequency')) {
                obj['frequency'] = DescriptionFrequency.constructFromObject(data['frequency']);
            }
            if (data.hasOwnProperty('includes')) {
                obj['includes'] = ApiClient.convertToType(data['includes'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} brand
 */
PackageDescription.prototype['brand'] = undefined;

/**
 * @member {String} brandLong
 */
PackageDescription.prototype['brandLong'] = undefined;

/**
 * @member {String} descShort
 */
PackageDescription.prototype['descShort'] = undefined;

/**
 * @member {String} descLong
 */
PackageDescription.prototype['descLong'] = undefined;

/**
 * @member {String} url
 */
PackageDescription.prototype['url'] = undefined;

/**
 * @member {String} days
 */
PackageDescription.prototype['days'] = undefined;

/**
 * @member {String} weekdays
 */
PackageDescription.prototype['weekdays'] = undefined;

/**
 * @member {module:model/DescriptionFrequency} frequency
 */
PackageDescription.prototype['frequency'] = undefined;

/**
 * @member {Array.<String>} includes
 */
PackageDescription.prototype['includes'] = undefined;






export default PackageDescription;

