/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Paper model module.
 * @module model/Paper
 * @version 1.3.0
 */
class Paper {
    /**
     * Constructs a new <code>Paper</code>.
     * @alias module:model/Paper
     * @param code {String} 
     * @param name {String} 
     */
    constructor(code, name) { 
        
        Paper.initialize(this, code, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, code, name) { 
        obj['code'] = code;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>Paper</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Paper} obj Optional instance to populate.
     * @return {module:model/Paper} The populated <code>Paper</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Paper();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} code
 */
Paper.prototype['code'] = undefined;

/**
 * @member {String} name
 */
Paper.prototype['name'] = undefined;






export default Paper;

