/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.3.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Persona) {
      root.Persona = {};
    }
    root.Persona.PausedSubscription = factory(root.Persona.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The PausedSubscription model module.
   * @module model/PausedSubscription
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>PausedSubscription</code>.
   * @alias module:model/PausedSubscription
   * @class
   * @param pausedSubscriptionSubsno {Number} 
   * @param pausedSubscriptionSleepStartDate {Date} 
   * @param pausedSubscriptionSleepEndDate {Date} 
   * @param pausedSubscriptionCreditType {String} 
   * @param pausedSubscriptionCreditAmount {Number} 
   * @param pausedSubscriptionSleepType {String} 
   * @param pausedSubscriptionCredited {Boolean} 
   * @param pausedSubscriptionCreditInvno {Number} 
   * @param pausedSubscriptionBookingDate {String} 
   * @param pausedSubscriptionAllowWebpaper {Boolean} 
   * @param pausedSubscriptionReceiveType {String} 
   * @param pausedSubscriptionConfirmStatus {String} 
   * @param pausedSubscriptionStampUser {String} 
   */
  var exports = function(pausedSubscriptionSubsno, pausedSubscriptionSleepStartDate, pausedSubscriptionSleepEndDate, pausedSubscriptionCreditType, pausedSubscriptionCreditAmount, pausedSubscriptionSleepType, pausedSubscriptionCredited, pausedSubscriptionCreditInvno, pausedSubscriptionBookingDate, pausedSubscriptionAllowWebpaper, pausedSubscriptionReceiveType, pausedSubscriptionConfirmStatus, pausedSubscriptionStampUser) {
    var _this = this;

    _this['pausedSubscriptionSubsno'] = pausedSubscriptionSubsno;
    _this['pausedSubscriptionSleepStartDate'] = pausedSubscriptionSleepStartDate;
    _this['pausedSubscriptionSleepEndDate'] = pausedSubscriptionSleepEndDate;
    _this['pausedSubscriptionCreditType'] = pausedSubscriptionCreditType;
    _this['pausedSubscriptionCreditAmount'] = pausedSubscriptionCreditAmount;
    _this['pausedSubscriptionSleepType'] = pausedSubscriptionSleepType;
    _this['pausedSubscriptionCredited'] = pausedSubscriptionCredited;
    _this['pausedSubscriptionCreditInvno'] = pausedSubscriptionCreditInvno;
    _this['pausedSubscriptionBookingDate'] = pausedSubscriptionBookingDate;
    _this['pausedSubscriptionAllowWebpaper'] = pausedSubscriptionAllowWebpaper;
    _this['pausedSubscriptionReceiveType'] = pausedSubscriptionReceiveType;
    _this['pausedSubscriptionConfirmStatus'] = pausedSubscriptionConfirmStatus;
    _this['pausedSubscriptionStampUser'] = pausedSubscriptionStampUser;
  };

  /**
   * Constructs a <code>PausedSubscription</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PausedSubscription} obj Optional instance to populate.
   * @return {module:model/PausedSubscription} The populated <code>PausedSubscription</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('pausedSubscriptionSubsno')) {
        obj['pausedSubscriptionSubsno'] = ApiClient.convertToType(data['pausedSubscriptionSubsno'], 'Number');
      }
      if (data.hasOwnProperty('pausedSubscriptionSleepStartDate')) {
        obj['pausedSubscriptionSleepStartDate'] = ApiClient.convertToType(data['pausedSubscriptionSleepStartDate'], 'Date');
      }
      if (data.hasOwnProperty('pausedSubscriptionSleepEndDate')) {
        obj['pausedSubscriptionSleepEndDate'] = ApiClient.convertToType(data['pausedSubscriptionSleepEndDate'], 'Date');
      }
      if (data.hasOwnProperty('pausedSubscriptionCreditType')) {
        obj['pausedSubscriptionCreditType'] = ApiClient.convertToType(data['pausedSubscriptionCreditType'], 'String');
      }
      if (data.hasOwnProperty('pausedSubscriptionCreditAmount')) {
        obj['pausedSubscriptionCreditAmount'] = ApiClient.convertToType(data['pausedSubscriptionCreditAmount'], 'Number');
      }
      if (data.hasOwnProperty('pausedSubscriptionSleepType')) {
        obj['pausedSubscriptionSleepType'] = ApiClient.convertToType(data['pausedSubscriptionSleepType'], 'String');
      }
      if (data.hasOwnProperty('pausedSubscriptionCredited')) {
        obj['pausedSubscriptionCredited'] = ApiClient.convertToType(data['pausedSubscriptionCredited'], 'Boolean');
      }
      if (data.hasOwnProperty('pausedSubscriptionCreditInvno')) {
        obj['pausedSubscriptionCreditInvno'] = ApiClient.convertToType(data['pausedSubscriptionCreditInvno'], 'Number');
      }
      if (data.hasOwnProperty('pausedSubscriptionBookingDate')) {
        obj['pausedSubscriptionBookingDate'] = ApiClient.convertToType(data['pausedSubscriptionBookingDate'], 'String');
      }
      if (data.hasOwnProperty('pausedSubscriptionAllowWebpaper')) {
        obj['pausedSubscriptionAllowWebpaper'] = ApiClient.convertToType(data['pausedSubscriptionAllowWebpaper'], 'Boolean');
      }
      if (data.hasOwnProperty('pausedSubscriptionReceiveType')) {
        obj['pausedSubscriptionReceiveType'] = ApiClient.convertToType(data['pausedSubscriptionReceiveType'], 'String');
      }
      if (data.hasOwnProperty('pausedSubscriptionConfirmStatus')) {
        obj['pausedSubscriptionConfirmStatus'] = ApiClient.convertToType(data['pausedSubscriptionConfirmStatus'], 'String');
      }
      if (data.hasOwnProperty('pausedSubscriptionStampUser')) {
        obj['pausedSubscriptionStampUser'] = ApiClient.convertToType(data['pausedSubscriptionStampUser'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Number} pausedSubscriptionSubsno
   */
  exports.prototype['pausedSubscriptionSubsno'] = undefined;
  /**
   * @member {Date} pausedSubscriptionSleepStartDate
   */
  exports.prototype['pausedSubscriptionSleepStartDate'] = undefined;
  /**
   * @member {Date} pausedSubscriptionSleepEndDate
   */
  exports.prototype['pausedSubscriptionSleepEndDate'] = undefined;
  /**
   * @member {String} pausedSubscriptionCreditType
   */
  exports.prototype['pausedSubscriptionCreditType'] = undefined;
  /**
   * @member {Number} pausedSubscriptionCreditAmount
   */
  exports.prototype['pausedSubscriptionCreditAmount'] = undefined;
  /**
   * @member {String} pausedSubscriptionSleepType
   */
  exports.prototype['pausedSubscriptionSleepType'] = undefined;
  /**
   * @member {Boolean} pausedSubscriptionCredited
   */
  exports.prototype['pausedSubscriptionCredited'] = undefined;
  /**
   * @member {Number} pausedSubscriptionCreditInvno
   */
  exports.prototype['pausedSubscriptionCreditInvno'] = undefined;
  /**
   * @member {String} pausedSubscriptionBookingDate
   */
  exports.prototype['pausedSubscriptionBookingDate'] = undefined;
  /**
   * @member {Boolean} pausedSubscriptionAllowWebpaper
   */
  exports.prototype['pausedSubscriptionAllowWebpaper'] = undefined;
  /**
   * @member {String} pausedSubscriptionReceiveType
   */
  exports.prototype['pausedSubscriptionReceiveType'] = undefined;
  /**
   * @member {String} pausedSubscriptionConfirmStatus
   */
  exports.prototype['pausedSubscriptionConfirmStatus'] = undefined;
  /**
   * @member {String} pausedSubscriptionStampUser
   */
  exports.prototype['pausedSubscriptionStampUser'] = undefined;



  return exports;
}));


