/**
 * Persona
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Persona) {
      root.Persona = {};
    }
    root.Persona.PausedSubscription = factory(root.Persona.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';



  /**
   * The PausedSubscription model module.
   * @module model/PausedSubscription
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>PausedSubscription</code>.
   * @alias module:model/PausedSubscription
   * @class
   * @param startDate {Date} 
   * @param endDate {Date} 
   * @param sleepType {module:model/PausedSubscription.SleepTypeEnum} Type of subscription pause
   */
  var exports = function(startDate, endDate, sleepType) {
    var _this = this;

    _this['startDate'] = startDate;
    _this['endDate'] = endDate;
    _this['sleepType'] = sleepType;
  };

  /**
   * Constructs a <code>PausedSubscription</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PausedSubscription} obj Optional instance to populate.
   * @return {module:model/PausedSubscription} The populated <code>PausedSubscription</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('startDate')) {
        obj['startDate'] = ApiClient.convertToType(data['startDate'], 'Date');
      }
      if (data.hasOwnProperty('endDate')) {
        obj['endDate'] = ApiClient.convertToType(data['endDate'], 'Date');
      }
      if (data.hasOwnProperty('sleepType')) {
        obj['sleepType'] = ApiClient.convertToType(data['sleepType'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Date} startDate
   */
  exports.prototype['startDate'] = undefined;
  /**
   * @member {Date} endDate
   */
  exports.prototype['endDate'] = undefined;
  /**
   * Type of subscription pause
   * @member {module:model/PausedSubscription.SleepTypeEnum} sleepType
   */
  exports.prototype['sleepType'] = undefined;


  /**
   * Allowed values for the <code>sleepType</code> property.
   * @enum {String}
   * @readonly
   */
  exports.SleepTypeEnum = {
    /**
     * value: "Pause"
     * @const
     */
    "Pause": "Pause",
    /**
     * value: "Rebate"
     * @const
     */
    "Rebate": "Rebate",
    /**
     * value: "UnknownSleepType"
     * @const
     */
    "UnknownSleepType": "UnknownSleepType"  };


  return exports;
}));


