/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PausedSubscription model module.
 * @module model/PausedSubscription
 * @version 1.3.0
 */
class PausedSubscription {
    /**
     * Constructs a new <code>PausedSubscription</code>.
     * @alias module:model/PausedSubscription
     * @param pausedSubscriptionSubsno {Number} 
     * @param pausedSubscriptionSleepStartDate {Date} 
     * @param pausedSubscriptionSleepEndDate {Date} 
     * @param pausedSubscriptionCreditType {String} 
     * @param pausedSubscriptionCreditAmount {Number} 
     * @param pausedSubscriptionSleepType {String} 
     * @param pausedSubscriptionCredited {Boolean} 
     * @param pausedSubscriptionCreditInvno {Number} 
     * @param pausedSubscriptionBookingDate {String} 
     * @param pausedSubscriptionAllowWebpaper {Boolean} 
     * @param pausedSubscriptionReceiveType {String} 
     * @param pausedSubscriptionConfirmStatus {String} 
     * @param pausedSubscriptionStampUser {String} 
     */
    constructor(pausedSubscriptionSubsno, pausedSubscriptionSleepStartDate, pausedSubscriptionSleepEndDate, pausedSubscriptionCreditType, pausedSubscriptionCreditAmount, pausedSubscriptionSleepType, pausedSubscriptionCredited, pausedSubscriptionCreditInvno, pausedSubscriptionBookingDate, pausedSubscriptionAllowWebpaper, pausedSubscriptionReceiveType, pausedSubscriptionConfirmStatus, pausedSubscriptionStampUser) { 
        
        PausedSubscription.initialize(this, pausedSubscriptionSubsno, pausedSubscriptionSleepStartDate, pausedSubscriptionSleepEndDate, pausedSubscriptionCreditType, pausedSubscriptionCreditAmount, pausedSubscriptionSleepType, pausedSubscriptionCredited, pausedSubscriptionCreditInvno, pausedSubscriptionBookingDate, pausedSubscriptionAllowWebpaper, pausedSubscriptionReceiveType, pausedSubscriptionConfirmStatus, pausedSubscriptionStampUser);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, pausedSubscriptionSubsno, pausedSubscriptionSleepStartDate, pausedSubscriptionSleepEndDate, pausedSubscriptionCreditType, pausedSubscriptionCreditAmount, pausedSubscriptionSleepType, pausedSubscriptionCredited, pausedSubscriptionCreditInvno, pausedSubscriptionBookingDate, pausedSubscriptionAllowWebpaper, pausedSubscriptionReceiveType, pausedSubscriptionConfirmStatus, pausedSubscriptionStampUser) { 
        obj['pausedSubscriptionSubsno'] = pausedSubscriptionSubsno;
        obj['pausedSubscriptionSleepStartDate'] = pausedSubscriptionSleepStartDate;
        obj['pausedSubscriptionSleepEndDate'] = pausedSubscriptionSleepEndDate;
        obj['pausedSubscriptionCreditType'] = pausedSubscriptionCreditType;
        obj['pausedSubscriptionCreditAmount'] = pausedSubscriptionCreditAmount;
        obj['pausedSubscriptionSleepType'] = pausedSubscriptionSleepType;
        obj['pausedSubscriptionCredited'] = pausedSubscriptionCredited;
        obj['pausedSubscriptionCreditInvno'] = pausedSubscriptionCreditInvno;
        obj['pausedSubscriptionBookingDate'] = pausedSubscriptionBookingDate;
        obj['pausedSubscriptionAllowWebpaper'] = pausedSubscriptionAllowWebpaper;
        obj['pausedSubscriptionReceiveType'] = pausedSubscriptionReceiveType;
        obj['pausedSubscriptionConfirmStatus'] = pausedSubscriptionConfirmStatus;
        obj['pausedSubscriptionStampUser'] = pausedSubscriptionStampUser;
    }

    /**
     * Constructs a <code>PausedSubscription</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PausedSubscription} obj Optional instance to populate.
     * @return {module:model/PausedSubscription} The populated <code>PausedSubscription</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PausedSubscription();

            if (data.hasOwnProperty('pausedSubscriptionSubsno')) {
                obj['pausedSubscriptionSubsno'] = ApiClient.convertToType(data['pausedSubscriptionSubsno'], 'Number');
            }
            if (data.hasOwnProperty('pausedSubscriptionSleepStartDate')) {
                obj['pausedSubscriptionSleepStartDate'] = ApiClient.convertToType(data['pausedSubscriptionSleepStartDate'], 'Date');
            }
            if (data.hasOwnProperty('pausedSubscriptionSleepEndDate')) {
                obj['pausedSubscriptionSleepEndDate'] = ApiClient.convertToType(data['pausedSubscriptionSleepEndDate'], 'Date');
            }
            if (data.hasOwnProperty('pausedSubscriptionCreditType')) {
                obj['pausedSubscriptionCreditType'] = ApiClient.convertToType(data['pausedSubscriptionCreditType'], 'String');
            }
            if (data.hasOwnProperty('pausedSubscriptionCreditAmount')) {
                obj['pausedSubscriptionCreditAmount'] = ApiClient.convertToType(data['pausedSubscriptionCreditAmount'], 'Number');
            }
            if (data.hasOwnProperty('pausedSubscriptionSleepType')) {
                obj['pausedSubscriptionSleepType'] = ApiClient.convertToType(data['pausedSubscriptionSleepType'], 'String');
            }
            if (data.hasOwnProperty('pausedSubscriptionCredited')) {
                obj['pausedSubscriptionCredited'] = ApiClient.convertToType(data['pausedSubscriptionCredited'], 'Boolean');
            }
            if (data.hasOwnProperty('pausedSubscriptionCreditInvno')) {
                obj['pausedSubscriptionCreditInvno'] = ApiClient.convertToType(data['pausedSubscriptionCreditInvno'], 'Number');
            }
            if (data.hasOwnProperty('pausedSubscriptionBookingDate')) {
                obj['pausedSubscriptionBookingDate'] = ApiClient.convertToType(data['pausedSubscriptionBookingDate'], 'String');
            }
            if (data.hasOwnProperty('pausedSubscriptionAllowWebpaper')) {
                obj['pausedSubscriptionAllowWebpaper'] = ApiClient.convertToType(data['pausedSubscriptionAllowWebpaper'], 'Boolean');
            }
            if (data.hasOwnProperty('pausedSubscriptionReceiveType')) {
                obj['pausedSubscriptionReceiveType'] = ApiClient.convertToType(data['pausedSubscriptionReceiveType'], 'String');
            }
            if (data.hasOwnProperty('pausedSubscriptionConfirmStatus')) {
                obj['pausedSubscriptionConfirmStatus'] = ApiClient.convertToType(data['pausedSubscriptionConfirmStatus'], 'String');
            }
            if (data.hasOwnProperty('pausedSubscriptionStampUser')) {
                obj['pausedSubscriptionStampUser'] = ApiClient.convertToType(data['pausedSubscriptionStampUser'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} pausedSubscriptionSubsno
 */
PausedSubscription.prototype['pausedSubscriptionSubsno'] = undefined;

/**
 * @member {Date} pausedSubscriptionSleepStartDate
 */
PausedSubscription.prototype['pausedSubscriptionSleepStartDate'] = undefined;

/**
 * @member {Date} pausedSubscriptionSleepEndDate
 */
PausedSubscription.prototype['pausedSubscriptionSleepEndDate'] = undefined;

/**
 * @member {String} pausedSubscriptionCreditType
 */
PausedSubscription.prototype['pausedSubscriptionCreditType'] = undefined;

/**
 * @member {Number} pausedSubscriptionCreditAmount
 */
PausedSubscription.prototype['pausedSubscriptionCreditAmount'] = undefined;

/**
 * @member {String} pausedSubscriptionSleepType
 */
PausedSubscription.prototype['pausedSubscriptionSleepType'] = undefined;

/**
 * @member {Boolean} pausedSubscriptionCredited
 */
PausedSubscription.prototype['pausedSubscriptionCredited'] = undefined;

/**
 * @member {Number} pausedSubscriptionCreditInvno
 */
PausedSubscription.prototype['pausedSubscriptionCreditInvno'] = undefined;

/**
 * @member {String} pausedSubscriptionBookingDate
 */
PausedSubscription.prototype['pausedSubscriptionBookingDate'] = undefined;

/**
 * @member {Boolean} pausedSubscriptionAllowWebpaper
 */
PausedSubscription.prototype['pausedSubscriptionAllowWebpaper'] = undefined;

/**
 * @member {String} pausedSubscriptionReceiveType
 */
PausedSubscription.prototype['pausedSubscriptionReceiveType'] = undefined;

/**
 * @member {String} pausedSubscriptionConfirmStatus
 */
PausedSubscription.prototype['pausedSubscriptionConfirmStatus'] = undefined;

/**
 * @member {String} pausedSubscriptionStampUser
 */
PausedSubscription.prototype['pausedSubscriptionStampUser'] = undefined;






export default PausedSubscription;

