/**
 * Persona
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FaroUser', 'model/JanrainUser'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./FaroUser'), require('./JanrainUser'));
  } else {
    // Browser globals (root is window)
    if (!root.Persona) {
      root.Persona = {};
    }
    root.Persona.SearchResult = factory(root.Persona.ApiClient, root.Persona.FaroUser, root.Persona.JanrainUser);
  }
}(this, function(ApiClient, FaroUser, JanrainUser) {
  'use strict';



  /**
   * The SearchResult model module.
   * @module model/SearchResult
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>SearchResult</code>.
   * @alias module:model/SearchResult
   * @class
   * @param faro {Array.<module:model/FaroUser>} 
   */
  var exports = function(faro) {
    var _this = this;

    _this['faro'] = faro;
  };

  /**
   * Constructs a <code>SearchResult</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SearchResult} obj Optional instance to populate.
   * @return {module:model/SearchResult} The populated <code>SearchResult</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('janrain')) {
        obj['janrain'] = JanrainUser.constructFromObject(data['janrain']);
      }
      if (data.hasOwnProperty('faro')) {
        obj['faro'] = ApiClient.convertToType(data['faro'], [FaroUser]);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/JanrainUser} janrain
   */
  exports.prototype['janrain'] = undefined;
  /**
   * @member {Array.<module:model/FaroUser>} faro
   */
  exports.prototype['faro'] = undefined;



  return exports;
}));


