/**
 * Persona
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Payment'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Payment'));
  } else {
    // Browser globals (root is window)
    if (!root.Persona) {
      root.Persona = {};
    }
    root.Persona.SubscriptionPayments = factory(root.Persona.ApiClient, root.Persona.Payment);
  }
}(this, function(ApiClient, Payment) {
  'use strict';



  /**
   * The SubscriptionPayments model module.
   * @module model/SubscriptionPayments
   * @version 1.3.0
   */

  /**
   * Constructs a new <code>SubscriptionPayments</code>.
   * @alias module:model/SubscriptionPayments
   * @class
   * @param subsno {Number} Product subsno
   * @param name {String} Package name
   * @param startDate {Date} 
   * @param lastDate {Date} 
   * @param payments {Array.<module:model/Payment>} Payments
   */
  var exports = function(subsno, name, startDate, lastDate, payments) {
    var _this = this;

    _this['subsno'] = subsno;
    _this['name'] = name;
    _this['startDate'] = startDate;
    _this['lastDate'] = lastDate;
    _this['payments'] = payments;
  };

  /**
   * Constructs a <code>SubscriptionPayments</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SubscriptionPayments} obj Optional instance to populate.
   * @return {module:model/SubscriptionPayments} The populated <code>SubscriptionPayments</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('subsno')) {
        obj['subsno'] = ApiClient.convertToType(data['subsno'], 'Number');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('startDate')) {
        obj['startDate'] = ApiClient.convertToType(data['startDate'], 'Date');
      }
      if (data.hasOwnProperty('lastDate')) {
        obj['lastDate'] = ApiClient.convertToType(data['lastDate'], 'Date');
      }
      if (data.hasOwnProperty('payments')) {
        obj['payments'] = ApiClient.convertToType(data['payments'], [Payment]);
      }
    }
    return obj;
  }

  /**
   * Product subsno
   * @member {Number} subsno
   */
  exports.prototype['subsno'] = undefined;
  /**
   * Package name
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {Date} startDate
   */
  exports.prototype['startDate'] = undefined;
  /**
   * @member {Date} lastDate
   */
  exports.prototype['lastDate'] = undefined;
  /**
   * Payments
   * @member {Array.<module:model/Payment>} payments
   */
  exports.prototype['payments'] = undefined;



  return exports;
}));


