/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.2.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Campaign', 'model/ModelPackage', 'model/SubscriptionDates'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Campaign'), require('./ModelPackage'), require('./SubscriptionDates'));
  } else {
    // Browser globals (root is window)
    if (!root.Persona) {
      root.Persona = {};
    }
    root.Persona.Subscription = factory(root.Persona.ApiClient, root.Persona.Campaign, root.Persona.ModelPackage, root.Persona.SubscriptionDates);
  }
}(this, function(ApiClient, Campaign, ModelPackage, SubscriptionDates) {
  'use strict';



  /**
   * The Subscription model module.
   * @module model/Subscription
   * @version 1.2.0
   */

  /**
   * Constructs a new <code>Subscription</code>.
   * @alias module:model/Subscription
   * @class
   * @param subsno {Number} 
   * @param extno {Number} 
   * @param cusno {Number} 
   * @param paycusno {Number} 
   * @param kind {String} 
   * @param state {String} 
   * @param _package {module:model/ModelPackage} 
   * @param dates {module:model/SubscriptionDates} 
   * @param extsubsexists {Boolean} 
   */
  var exports = function(subsno, extno, cusno, paycusno, kind, state, _package, dates, extsubsexists) {
    var _this = this;

    _this['subsno'] = subsno;
    _this['extno'] = extno;
    _this['cusno'] = cusno;
    _this['paycusno'] = paycusno;
    _this['kind'] = kind;
    _this['state'] = state;
    _this['package'] = _package;
    _this['dates'] = dates;
    _this['extsubsexists'] = extsubsexists;
  };

  /**
   * Constructs a <code>Subscription</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Subscription} obj Optional instance to populate.
   * @return {module:model/Subscription} The populated <code>Subscription</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('subsno')) {
        obj['subsno'] = ApiClient.convertToType(data['subsno'], 'Number');
      }
      if (data.hasOwnProperty('extno')) {
        obj['extno'] = ApiClient.convertToType(data['extno'], 'Number');
      }
      if (data.hasOwnProperty('cusno')) {
        obj['cusno'] = ApiClient.convertToType(data['cusno'], 'Number');
      }
      if (data.hasOwnProperty('paycusno')) {
        obj['paycusno'] = ApiClient.convertToType(data['paycusno'], 'Number');
      }
      if (data.hasOwnProperty('kind')) {
        obj['kind'] = ApiClient.convertToType(data['kind'], 'String');
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
      if (data.hasOwnProperty('pricegroup')) {
        obj['pricegroup'] = ApiClient.convertToType(data['pricegroup'], 'String');
      }
      if (data.hasOwnProperty('package')) {
        obj['package'] = ModelPackage.constructFromObject(data['package']);
      }
      if (data.hasOwnProperty('dates')) {
        obj['dates'] = SubscriptionDates.constructFromObject(data['dates']);
      }
      if (data.hasOwnProperty('extsubsexists')) {
        obj['extsubsexists'] = ApiClient.convertToType(data['extsubsexists'], 'Boolean');
      }
      if (data.hasOwnProperty('campaign')) {
        obj['campaign'] = Campaign.constructFromObject(data['campaign']);
      }
    }
    return obj;
  }

  /**
   * @member {Number} subsno
   */
  exports.prototype['subsno'] = undefined;
  /**
   * @member {Number} extno
   */
  exports.prototype['extno'] = undefined;
  /**
   * @member {Number} cusno
   */
  exports.prototype['cusno'] = undefined;
  /**
   * @member {Number} paycusno
   */
  exports.prototype['paycusno'] = undefined;
  /**
   * @member {String} kind
   */
  exports.prototype['kind'] = undefined;
  /**
   * @member {String} state
   */
  exports.prototype['state'] = undefined;
  /**
   * @member {String} pricegroup
   */
  exports.prototype['pricegroup'] = undefined;
  /**
   * @member {module:model/ModelPackage} package
   */
  exports.prototype['package'] = undefined;
  /**
   * @member {module:model/SubscriptionDates} dates
   */
  exports.prototype['dates'] = undefined;
  /**
   * @member {Boolean} extsubsexists
   */
  exports.prototype['extsubsexists'] = undefined;
  /**
   * @member {module:model/Campaign} campaign
   */
  exports.prototype['campaign'] = undefined;



  return exports;
}));


