/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SubscriptionPauseDates model module.
 * @module model/SubscriptionPauseDates
 * @version 1.3.0
 */
class SubscriptionPauseDates {
    /**
     * Constructs a new <code>SubscriptionPauseDates</code>.
     * @alias module:model/SubscriptionPauseDates
     * @param startDate {Date} 
     * @param endDate {Date} 
     */
    constructor(startDate, endDate) { 
        
        SubscriptionPauseDates.initialize(this, startDate, endDate);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, startDate, endDate) { 
        obj['startDate'] = startDate;
        obj['endDate'] = endDate;
    }

    /**
     * Constructs a <code>SubscriptionPauseDates</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubscriptionPauseDates} obj Optional instance to populate.
     * @return {module:model/SubscriptionPauseDates} The populated <code>SubscriptionPauseDates</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubscriptionPauseDates();

            if (data.hasOwnProperty('startDate')) {
                obj['startDate'] = ApiClient.convertToType(data['startDate'], 'Date');
            }
            if (data.hasOwnProperty('endDate')) {
                obj['endDate'] = ApiClient.convertToType(data['endDate'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {Date} startDate
 */
SubscriptionPauseDates.prototype['startDate'] = undefined;

/**
 * @member {Date} endDate
 */
SubscriptionPauseDates.prototype['endDate'] = undefined;






export default SubscriptionPauseDates;

