/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SubscriptionDates model module.
 * @module model/SubscriptionDates
 * @version 1.3.0
 */
class SubscriptionDates {
    /**
     * Constructs a new <code>SubscriptionDates</code>.
     * @alias module:model/SubscriptionDates
     * @param start {Date} 
     */
    constructor(start) { 
        
        SubscriptionDates.initialize(this, start);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, start) { 
        obj['start'] = start;
    }

    /**
     * Constructs a <code>SubscriptionDates</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubscriptionDates} obj Optional instance to populate.
     * @return {module:model/SubscriptionDates} The populated <code>SubscriptionDates</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubscriptionDates();

            if (data.hasOwnProperty('lenMonths')) {
                obj['lenMonths'] = ApiClient.convertToType(data['lenMonths'], 'Number');
            }
            if (data.hasOwnProperty('lenDays')) {
                obj['lenDays'] = ApiClient.convertToType(data['lenDays'], 'Number');
            }
            if (data.hasOwnProperty('start')) {
                obj['start'] = ApiClient.convertToType(data['start'], 'Date');
            }
            if (data.hasOwnProperty('end')) {
                obj['end'] = ApiClient.convertToType(data['end'], 'Date');
            }
            if (data.hasOwnProperty('unpaidBreak')) {
                obj['unpaidBreak'] = ApiClient.convertToType(data['unpaidBreak'], 'Date');
            }
            if (data.hasOwnProperty('invoicingStart')) {
                obj['invoicingStart'] = ApiClient.convertToType(data['invoicingStart'], 'Date');
            }
            if (data.hasOwnProperty('paidUntil')) {
                obj['paidUntil'] = ApiClient.convertToType(data['paidUntil'], 'Date');
            }
            if (data.hasOwnProperty('suspend')) {
                obj['suspend'] = ApiClient.convertToType(data['suspend'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} lenMonths
 */
SubscriptionDates.prototype['lenMonths'] = undefined;

/**
 * @member {Number} lenDays
 */
SubscriptionDates.prototype['lenDays'] = undefined;

/**
 * @member {Date} start
 */
SubscriptionDates.prototype['start'] = undefined;

/**
 * @member {Date} end
 */
SubscriptionDates.prototype['end'] = undefined;

/**
 * @member {Date} unpaidBreak
 */
SubscriptionDates.prototype['unpaidBreak'] = undefined;

/**
 * @member {Date} invoicingStart
 */
SubscriptionDates.prototype['invoicingStart'] = undefined;

/**
 * @member {Date} paidUntil
 */
SubscriptionDates.prototype['paidUntil'] = undefined;

/**
 * @member {Date} suspend
 */
SubscriptionDates.prototype['suspend'] = undefined;






export default SubscriptionDates;

