/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Address from './Address';
import GdprConsent from './GdprConsent';
import LegalConsent from './LegalConsent';
import Subscription from './Subscription';

/**
 * The User model module.
 * @module model/User
 * @version 1.3.0
 */
class User {
    /**
     * Constructs a new <code>User</code>.
     * @alias module:model/User
     * @param uuid {String} 
     * @param email {String} 
     * @param cusno {String} 
     * @param subs {Array.<module:model/Subscription>} 
     * @param consent {Array.<module:model/GdprConsent>} 
     * @param legal {Array.<module:model/LegalConsent>} 
     */
    constructor(uuid, email, cusno, subs, consent, legal) { 
        
        User.initialize(this, uuid, email, cusno, subs, consent, legal);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, uuid, email, cusno, subs, consent, legal) { 
        obj['uuid'] = uuid;
        obj['email'] = email;
        obj['cusno'] = cusno;
        obj['subs'] = subs;
        obj['consent'] = consent;
        obj['legal'] = legal;
    }

    /**
     * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/User} obj Optional instance to populate.
     * @return {module:model/User} The populated <code>User</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new User();

            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = Address.constructFromObject(data['address']);
            }
            if (data.hasOwnProperty('cusno')) {
                obj['cusno'] = ApiClient.convertToType(data['cusno'], 'String');
            }
            if (data.hasOwnProperty('subs')) {
                obj['subs'] = ApiClient.convertToType(data['subs'], [Subscription]);
            }
            if (data.hasOwnProperty('consent')) {
                obj['consent'] = ApiClient.convertToType(data['consent'], [GdprConsent]);
            }
            if (data.hasOwnProperty('legal')) {
                obj['legal'] = ApiClient.convertToType(data['legal'], [LegalConsent]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} uuid
 */
User.prototype['uuid'] = undefined;

/**
 * @member {String} email
 */
User.prototype['email'] = undefined;

/**
 * @member {String} firstName
 */
User.prototype['firstName'] = undefined;

/**
 * @member {String} lastName
 */
User.prototype['lastName'] = undefined;

/**
 * @member {module:model/Address} address
 */
User.prototype['address'] = undefined;

/**
 * @member {String} cusno
 */
User.prototype['cusno'] = undefined;

/**
 * @member {Array.<module:model/Subscription>} subs
 */
User.prototype['subs'] = undefined;

/**
 * @member {Array.<module:model/GdprConsent>} consent
 */
User.prototype['consent'] = undefined;

/**
 * @member {Array.<module:model/LegalConsent>} legal
 */
User.prototype['legal'] = undefined;






export default User;

