/**
 * Persona
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Persona);
  }
}(this, function(expect, Persona) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Persona.JanrainUser();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('JanrainUser', function() {
    it('should create an instance of JanrainUser', function() {
      // uncomment below and update the code to test JanrainUser
      //var instance = new Persona.JanrainUser();
      //expect(instance).to.be.a(Persona.JanrainUser);
    });

    it('should have the property uuid (base name: "uuid")', function() {
      // uncomment below and update the code to test the property uuid
      //var instance = new Persona.JanrainUser();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new Persona.JanrainUser();
      //expect(instance).to.be();
    });

    it('should have the property firstName (base name: "firstName")', function() {
      // uncomment below and update the code to test the property firstName
      //var instance = new Persona.JanrainUser();
      //expect(instance).to.be();
    });

    it('should have the property lastName (base name: "lastName")', function() {
      // uncomment below and update the code to test the property lastName
      //var instance = new Persona.JanrainUser();
      //expect(instance).to.be();
    });

    it('should have the property middleName (base name: "middleName")', function() {
      // uncomment below and update the code to test the property middleName
      //var instance = new Persona.JanrainUser();
      //expect(instance).to.be();
    });

    it('should have the property consent (base name: "consent")', function() {
      // uncomment below and update the code to test the property consent
      //var instance = new Persona.JanrainUser();
      //expect(instance).to.be();
    });

    it('should have the property legal (base name: "legal")', function() {
      // uncomment below and update the code to test the property legal
      //var instance = new Persona.JanrainUser();
      //expect(instance).to.be();
    });

    it('should have the property cusno (base name: "cusno")', function() {
      // uncomment below and update the code to test the property cusno
      //var instance = new Persona.JanrainUser();
      //expect(instance).to.be();
    });

    it('should have the property otherCusnos (base name: "otherCusnos")', function() {
      // uncomment below and update the code to test the property otherCusnos
      //var instance = new Persona.JanrainUser();
      //expect(instance).to.be();
    });

  });

}));
