/**
 * Persona
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Persona);
  }
}(this, function(expect, Persona) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Persona.NewUser();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('NewUser', function() {
    it('should create an instance of NewUser', function() {
      // uncomment below and update the code to test NewUser
      //var instance = new Persona.NewUser();
      //expect(instance).to.be.a(Persona.NewUser);
    });

    it('should have the property newUserFirstName (base name: "newUserFirstName")', function() {
      // uncomment below and update the code to test the property newUserFirstName
      //var instance = new Persona.NewUser();
      //expect(instance).to.be();
    });

    it('should have the property newUserLastName (base name: "newUserLastName")', function() {
      // uncomment below and update the code to test the property newUserLastName
      //var instance = new Persona.NewUser();
      //expect(instance).to.be();
    });

    it('should have the property newUserEmailAddress (base name: "newUserEmailAddress")', function() {
      // uncomment below and update the code to test the property newUserEmailAddress
      //var instance = new Persona.NewUser();
      //expect(instance).to.be();
    });

    it('should have the property newUserPassword (base name: "newUserPassword")', function() {
      // uncomment below and update the code to test the property newUserPassword
      //var instance = new Persona.NewUser();
      //expect(instance).to.be();
    });

    it('should have the property newUserConfirmPassword (base name: "newUserConfirmPassword")', function() {
      // uncomment below and update the code to test the property newUserConfirmPassword
      //var instance = new Persona.NewUser();
      //expect(instance).to.be();
    });

    it('should have the property newUserStreetAddress (base name: "newUserStreetAddress")', function() {
      // uncomment below and update the code to test the property newUserStreetAddress
      //var instance = new Persona.NewUser();
      //expect(instance).to.be();
    });

    it('should have the property newUserZipCode (base name: "newUserZipCode")', function() {
      // uncomment below and update the code to test the property newUserZipCode
      //var instance = new Persona.NewUser();
      //expect(instance).to.be();
    });

    it('should have the property newUserCity (base name: "newUserCity")', function() {
      // uncomment below and update the code to test the property newUserCity
      //var instance = new Persona.NewUser();
      //expect(instance).to.be();
    });

    it('should have the property newUserCountry (base name: "newUserCountry")', function() {
      // uncomment below and update the code to test the property newUserCountry
      //var instance = new Persona.NewUser();
      //expect(instance).to.be();
    });

    it('should have the property newUserPhone (base name: "newUserPhone")', function() {
      // uncomment below and update the code to test the property newUserPhone
      //var instance = new Persona.NewUser();
      //expect(instance).to.be();
    });

  });

}));
