/**
 * Persona
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.1-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Persona);
  }
}(this, function(expect, Persona) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Persona.Payment();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Payment', function() {
    it('should create an instance of Payment', function() {
      // uncomment below and update the code to test Payment
      //var instance = new Persona.Payment();
      //expect(instance).to.be.a(Persona.Payment);
    });

    it('should have the property invno (base name: "invno")', function() {
      // uncomment below and update the code to test the property invno
      //var instance = new Persona.Payment();
      //expect(instance).to.be();
    });

    it('should have the property _date (base name: "date")', function() {
      // uncomment below and update the code to test the property _date
      //var instance = new Persona.Payment();
      //expect(instance).to.be();
    });

    it('should have the property dueDate (base name: "dueDate")', function() {
      // uncomment below and update the code to test the property dueDate
      //var instance = new Persona.Payment();
      //expect(instance).to.be();
    });

    it('should have the property expenses (base name: "expenses")', function() {
      // uncomment below and update the code to test the property expenses
      //var instance = new Persona.Payment();
      //expect(instance).to.be();
    });

    it('should have the property interest (base name: "interest")', function() {
      // uncomment below and update the code to test the property interest
      //var instance = new Persona.Payment();
      //expect(instance).to.be();
    });

    it('should have the property vat (base name: "vat")', function() {
      // uncomment below and update the code to test the property vat
      //var instance = new Persona.Payment();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new Persona.Payment();
      //expect(instance).to.be();
    });

    it('should have the property openAmount (base name: "openAmount")', function() {
      // uncomment below and update the code to test the property openAmount
      //var instance = new Persona.Payment();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new Persona.Payment();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new Persona.Payment();
      //expect(instance).to.be();
    });

    it('should have the property discPercent (base name: "discPercent")', function() {
      // uncomment below and update the code to test the property discPercent
      //var instance = new Persona.Payment();
      //expect(instance).to.be();
    });

    it('should have the property discAmount (base name: "discAmount")', function() {
      // uncomment below and update the code to test the property discAmount
      //var instance = new Persona.Payment();
      //expect(instance).to.be();
    });

  });

}));
