/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 3.1.2-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Persona);
  }
}(this, function(expect, Persona) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Persona.Subscription();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Subscription', function() {
    it('should create an instance of Subscription', function() {
      // uncomment below and update the code to test Subscription
      //var instance = new Persona.Subscription();
      //expect(instance).to.be.a(Persona.Subscription);
    });

    it('should have the property subsno (base name: "subsno")', function() {
      // uncomment below and update the code to test the property subsno
      //var instance = new Persona.Subscription();
      //expect(instance).to.be();
    });

    it('should have the property extno (base name: "extno")', function() {
      // uncomment below and update the code to test the property extno
      //var instance = new Persona.Subscription();
      //expect(instance).to.be();
    });

    it('should have the property cusno (base name: "cusno")', function() {
      // uncomment below and update the code to test the property cusno
      //var instance = new Persona.Subscription();
      //expect(instance).to.be();
    });

    it('should have the property paycusno (base name: "paycusno")', function() {
      // uncomment below and update the code to test the property paycusno
      //var instance = new Persona.Subscription();
      //expect(instance).to.be();
    });

    it('should have the property kind (base name: "kind")', function() {
      // uncomment below and update the code to test the property kind
      //var instance = new Persona.Subscription();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new Persona.Subscription();
      //expect(instance).to.be();
    });

    it('should have the property pricegroup (base name: "pricegroup")', function() {
      // uncomment below and update the code to test the property pricegroup
      //var instance = new Persona.Subscription();
      //expect(instance).to.be();
    });

    it('should have the property _package (base name: "package")', function() {
      // uncomment below and update the code to test the property _package
      //var instance = new Persona.Subscription();
      //expect(instance).to.be();
    });

    it('should have the property dates (base name: "dates")', function() {
      // uncomment below and update the code to test the property dates
      //var instance = new Persona.Subscription();
      //expect(instance).to.be();
    });

    it('should have the property extsubsexists (base name: "extsubsexists")', function() {
      // uncomment below and update the code to test the property extsubsexists
      //var instance = new Persona.Subscription();
      //expect(instance).to.be();
    });

    it('should have the property campaign (base name: "campaign")', function() {
      // uncomment below and update the code to test the property campaign
      //var instance = new Persona.Subscription();
      //expect(instance).to.be();
    });

  });

}));
